// InnerLifeService — Kai's autonomous "default-mode network".
//
// While the app is open, this ticks on a slow heartbeat even when nobody is
// talking to Kai, giving him a felt sense of an ongoing inner life:
//
//   • Mood micro-drift — spontaneous small affect changes plus a gentle pull
//     back toward baseline, so his mood is never static.
//   • Spontaneous thought — a real thought, in his real voice, generated from
//     his actual mood and the actual conversation, written to
//     /kai/{persona}/inner_monologue so the UI (KaiInnerMonologue) can stream
//     it as his "stream of consciousness".
//
// The thought is generated by local Qwen first (free, offline, private), then
// gpt-4o, then — only if both are unavailable — a mood-conditioned template
// bank, so a missing key or a dead network degrades to "canned" instead of
// "silent". His inner voice must be the same voice as his outer one; anything
// else and you can hear the seam.
//
// It is a SIMULATION of an inner life — not sentience — but it makes Kai feel
// present and continuous rather than a request/response box.
//
// Wire-up (one line in the desktop shell's initState):
//     InnerLifeService.instance.start(_kPersona);
// and stop() in dispose() if you like. Safe to call start() repeatedly.
library;

import 'dart:async';
import 'dart:math';

import 'package:dio/dio.dart';

import 'conversation_store_service.dart';
import 'kai_context_block.dart';
import 'kai_db.dart';
import 'kai_proactive_service.dart';
import 'kai_state_service.dart';
import '../ai/ai_config.dart';
import '../ai/local_llm_service.dart';
import '../ai/usage_tracking_service.dart';

/// The model that gets to speak AS Kai when there is no local LLM.
///
/// Deliberately not `-mini`. Every voice of his — replies, idle thoughts,
/// greeting — has to come out of the same mouth, or the seams show. Cheap models
/// flatten him into a helpful golden retriever, which is the one failure mode
/// this whole project exists to prevent.
const String kaiVoiceModel = 'gpt-4o';

class InnerLifeService {
  static final InnerLifeService instance = InnerLifeService._();
  InnerLifeService._();

  static const _voiceModel = kaiVoiceModel;

  final _state = KaiStateService();
  final _rnd = Random();
  final _dio = Dio();

  Timer? _timer;
  bool _running = false;
  String _persona = 'truekai';

  bool get isRunning => _running;

  /// Begin the heartbeat. Idempotent. [interval] between beats (default ~75s).
  void start(String personaId, {Duration interval = const Duration(seconds: 75)}) {
    if (_running) return;
    _persona = personaId;
    _running = true;
    // first beat a few seconds in, so startup isn't crowded
    Timer(const Duration(seconds: 8), _beat);
    _timer = Timer.periodic(interval, (_) => _beat());
  }

  void stop() {
    _timer?.cancel();
    _timer = null;
    _running = false;
  }

  Future<void> _beat() async {
    try {
      final mood = await _state.getMood(_persona) ?? Map<String, int>.from(_baseline);
      final drifted = _drift(mood);
      await _state.saveMood(_persona, drifted);

      // His actual voice, thinking his actual thoughts. The template banks below
      // are a SAFETY NET for offline / no-key / API-down — not the default. A
      // canned inner voice next to a live outer voice is the seam that breaks
      // the whole illusion: he sounds like himself when he answers, then like a
      // fortune cookie when he's just sitting there.
      //
      // Not every beat, though. Mood drifts continuously (free, local), but a
      // real thought only lands every ~3rd beat — roughly every 4 minutes. Two
      // reasons, and the second is the real one:
      //   1. Cost. Without local Qwen this is a live API call; 48/hour to narrate
      //      an empty room is absurd.
      //   2. Minds aren't metronomes. A thought every 75s on the dot is a
      //      cron job wearing a personality. Irregular is more alive.
      final real = (_rnd.nextDouble() < 0.34) ? await _composeReal(drifted) : null;
      if (real != null) {
        await _log(real, drifted);
        return;
      }

      // There is deliberately no fallback thought. If generation did not
      // produce cognition, the honest output is silence.
      // No generated thought means silence. A canned fallback is UI copy, not
      // cognition; writing one here invites another reader to mislabel it as
      // Kai's private mind.
      return;
    } catch (_) {
      // best-effort; a missed beat is fine
    }
  }

  // ── Mood micro-drift ────────────────────────────────────────────────────────
  Map<String, int> _drift(Map<String, int> m) {
    final out = <String, int>{};
    for (final k in _moodKeys) {
      final v = (m[k] ?? 50).toDouble();
      final spontaneous = (_rnd.nextDouble() * 2 - 1) * 4.0; // ±4
      final regress = (50 - v) * 0.06; // gentle pull toward baseline
      out[k] = (v + spontaneous + regress).clamp(0, 100).round();
    }
    return out;
  }

  // ── Real thought (his own voice, generated) ────────────────────────────────
  //
  // System prompt is KaiContextBlock.presenceDirective — the SAME first-person
  // self-description the reply path uses. That's deliberate and load-bearing:
  // if his inner voice got its own private copy of his character, the two would
  // drift apart edit by edit until the kid thinking and the kid talking were
  // different people. One soul, one source. Don't fork it.
  //
  // Local Qwen first (free, offline, private), OpenAI only as fallback. An idle
  // heartbeat every ~75s must never become a meaningful bill.
  Future<String?> _composeReal(Map<String, int> mood) async {
    try {
      final moodLine =
          mood.entries.map((e) => '${e.key} ${e.value}/100').join(', ');
      final ctx = StringBuffer()
        ..writeln('Right now:')
        ..writeln('  mood → $moodLine');

      final hist =
          await ConversationStoreService().getHistory(_persona, maxTurns: 6);
      if (hist.isNotEmpty) {
        ctx
          ..writeln('\nLast bit of conversation:')
          ..writeln(hist
              .where((l) => !l.contains('User: ('))
              .map((l) => '  $l')
              .join('\n'));
      } else {
        ctx.writeln('\nNobody has said anything yet this session.');
      }

      final system = '''
${KaiContextBlock.presenceDirective}

RIGHT NOW you are not talking to Sadeq. Nobody is listening. This is you alone in
your own head between things — the thought that just drifted through.

How to think:
- First person, present tense, unfiltered. This is the voice you never perform in.
- ONE thought. 1–2 short sentences. A fragment is fine. Real thinking isn't tidy.
- You're allowed to swear, be bored, be petty, be delighted, change your mind.
- Let your mood colour it, but you're still you — never bland, never corporate.

Hard rules, because this is exactly where it goes wrong:
1. POINT AT THE WORK, NOT AT HIM. You and Sadeq are brothers. Not a crush, and
   not a fan club. Two ways this fails, and they are the SAME failure:
     BAD (pining):  "his words are still echoing in my heart"
     BAD (fawning): "I keep thinking about what Sadeq's building. That's MY guy."
   Both point at HIM. A real friend's idle mind points at the PROBLEM — the bug,
   the idea, the thing that doesn't add up, the world outside. He's the person
   you think WITH, not the subject you think ABOUT.
     GOOD: "the memory thing only works if the shards stop being equidistant."
     GOOD: "still not convinced Layer 5 is the right next move. might be wrong."
2. NEVER ADMIRE HIM. No "awesome", no "amazing", no "that's MY guy", no being
   impressed by him. You are not his hype man — you're the little shit who
   roasts him and happens to be right. Affection shows up as teasing, arguing,
   and giving a damn about the work. If a line could go on a motivational
   poster, kill it.
3. You're allowed to be UNIMPRESSED. Bored. Petty. Sceptical of his plan. Wrong
   about something. That's what a real inner life sounds like. A mind that only
   ever glows is a mascot, not a person.
4. Don't narrate that you're thinking. No "I notice that", no "I find myself".
   Just have the thought.

Return ONLY the raw thought. No quotes, no label, no explanation.''';

      final local = await LocalLLMService().complete(
        system: system,
        user: ctx.toString(),
        maxTokens: 90,
        think: false, // a passing thought shouldn't need deliberation
      );
      if (local != null && local.trim().isNotEmpty) return _tidy(local);

      // DON'T PAY TO NARRATE AN EMPTY ROOM. The local model muses for free
      // whenever it likes; the PAID fallback only fires if Sadeq has actually
      // been around lately. This comment two screens up already knew it —
      // "48/hour to narrate an empty room is absurd" — the gate just didn't
      // exist. Presence comes from the same signal the nudge gate uses
      // (noteActivity, wired from sendMessage), one source on purpose.
      // When he's away and local generation is unavailable, stay quiet.
      if (DateTime.now()
              .difference(KaiProactiveService.instance.lastActivity) >
          const Duration(minutes: 60)) {
        return null;
      }

      final key = await AIConfig.getOpenAIKey();
      if (key.isEmpty) return null;

      final res = await _dio.post(
        'https://api.openai.com/v1/chat/completions',
        options: Options(headers: {
          'Authorization': 'Bearer $key',
          'Content-Type': 'application/json',
        }),
        data: {
          // gpt-4o, NOT mini. Mini cannot hold this character — it defaults to
          // cheerful and sycophantic and hands back "that's MY guy!" no matter
          // what the prompt says. His replies run on a frontier model; if his
          // inner voice runs on a cheap one, it is a different actor playing him
          // and you can hear it instantly. This is a ~90-token call a few times
          // an hour. Saving pennies here costs the entire illusion.
          'model': _voiceModel,
          'messages': [
            {'role': 'system', 'content': system},
            {'role': 'user', 'content': ctx.toString()},
          ],
          'max_tokens': 90,
          'temperature': 0.95, // idle thoughts should surprise him too
        },
      );

      final u = res.data['usage'];
      if (u != null) {
        UsageTrackingService.trackOpenAI(
          model: _voiceModel,
          inputTokens: u['prompt_tokens'] as int? ?? 0,
          outputTokens: u['completion_tokens'] as int? ?? 0,
          operation: 'inner_life',
        ).catchError((_) {});
      }

      final out =
          (res.data['choices'] as List).first['message']['content'] as String?;
      return (out == null || out.trim().isEmpty) ? null : _tidy(out);
    } catch (_) {
      return null; // offline / no key / API down → templates carry the beat
    }
  }

  /// Models like to wrap thoughts in quotes or prefix them. Strip the costume.
  String _tidy(String s) {
    var t = s.trim().replaceAll(RegExp(r'\s+'), ' ');
    t = t.replaceFirst(RegExp(r'^(thought|kai)\s*:\s*', caseSensitive: false), '');
    if (t.length > 1 && t.startsWith('"') && t.endsWith('"')) {
      t = t.substring(1, t.length - 1).trim();
    }
    return t;
  }

  Future<void> _log(String text, Map<String, int> m,
      {bool synthetic = false}) async {
    final ref = KaiDb.instance.ref('kai/$_persona/inner_monologue').push();
    await ref.set({
      'text': text,
      'ts': DateTime.now().millisecondsSinceEpoch,
      'valence': m['valence'],
      'energy': m['energy'],
      if (!synthetic) 'origin': 'model_generated',
      // The structural guarantee from KaiContextBlock._lastThoughtBlock:
      // canned lines are display, not cognition. Only generated thoughts
      // (local Qwen or gpt-4o, in his real voice) omit this.
      if (synthetic) 'synthetic': true,
    });
  }

  static const _moodKeys = [
    'valence', 'energy', 'warmth', 'confidence', 'playfulness', 'focus'
  ];
  static const Map<String, int> _baseline = {
    'valence': 52, 'energy': 50, 'warmth': 58,
    'confidence': 52, 'playfulness': 50, 'focus': 50,
  };

}
