"""
Kai AI Input Driver - Receives intelligent ambiance commands from homecoming app
Gets music search prompts and lighting configs from Kai's analysis
"""

import logging
import firebase_admin
from firebase_admin import db
from typing import Dict, Any, Optional
import asyncio

from ..core.driver_base import InputDriver, DriverConfig

logger = logging.getLogger(__name__)


class KaiAIInputDriver(InputDriver):
    """
    Listen to Firebase for ambiance commands from the homecoming app.
    Kai analyzes the user's natural language input and sends:
    - Music mood/search prompt
    - Lighting color/effect/brightness
    - Confidence level
    
    The fixture receives these and routes to appropriate output drivers.
    """
    
    def __init__(self, config: DriverConfig):
        super().__init__(config)
        self.firebase_ref = None
        self.is_listening = False
        self.last_command = None
        self.persona_id = config.params.get('persona_id', 'kai_persona_1')
        self.device_id = config.params.get('device_id', 'raspberry_pi_home')
        self.command_queue: asyncio.Queue = asyncio.Queue()
    
    async def start(self) -> bool:
        """Start listening for Firebase commands"""
        try:
            # Initialize Firebase if not already done
            try:
                if firebase_admin._apps:
                    self.logger.info("Firebase already initialized")
                else:
                    # Will need credentials set up on Pi
                    firebase_admin.initialize_app()
            except (ValueError, AttributeError):
                # App already initialized or _apps attribute missing
                pass
            
            self.firebase_ref = db.reference(f'home_automation/{self.persona_id}/commands')
            self.is_listening = True
            
            # Start listening for new commands
            self._listen_for_commands()
            
            self.logger.info(f"🎤 Kai AI input driver started (listening to {self.persona_id})")
            return True
            
        except Exception as e:
            self.logger.error(f"❌ Failed to start Kai AI driver: {e}")
            return False
    
    def _listen_for_commands(self):
        """Set up Firebase listener for ambiance commands"""
        try:
            def on_new_command(message):
                """Called when a new command arrives from Firebase"""
                if message.event == 'put':
                    command_id = message.path.split('/')[-1]
                    command_data = message.data
                    
                    # Skip if this is our own command echo
                    if self.last_command == command_id:
                        return
                    
                    self.logger.info(f"📡 Received command from homecoming app: {command_id}")
                    self.logger.debug(f"Command data: {command_data}")
                    
                    # Queue the command for processing
                    asyncio.create_task(self.command_queue.put({
                        'command_id': command_id,
                        'data': command_data
                    }))
            
            # Start listening
            self.firebase_ref.listen(on_new_command)
            
        except Exception as e:
            self.logger.error(f"❌ Firebase listener error: {e}")
    
    async def stop(self):
        """Stop listening for commands"""
        self.is_listening = False
        self.logger.info("🎤 Kai AI input driver stopped")
    
    async def is_ready(self) -> bool:
        """Check if listening is active"""
        return self.is_listening
    
    async def get_command(self, timeout_ms: int = 5000) -> Optional[Dict[str, Any]]:
        """
        Get next command from Firebase queue.
        
        Returns command like:
        {
            'device': 'raspberry_pi_home',
            'target': 'ambiance',
            'action': 'dnd_ambiance',
            'params': {
                'prompt': 'tavern music',
                'include_music': True,
                'include_smoke': False
            }
        }
        """
        try:
            timeout_s = timeout_ms / 1000.0
            command = await asyncio.wait_for(self.command_queue.get(), timeout=timeout_s)
            self.last_command = command.get('command_id')
            return command.get('data')
        except asyncio.TimeoutError:
            return None
        except Exception as e:
            self.logger.error(f"❌ Error getting command: {e}")
            return None


class KaiCommandInterpreter:
    """
    Dynamically interprets Firebase commands from Kai AI based on conversation context.
    
    Instead of hardcoded scenes, Kai analyzes the conversation and provides:
    - music_prompt: What to search for on YouTube (generated by Kai from context)
    - lighting_config: Color, effect, brightness (intelligently mapped from mood/intensity)
    
    This allows infinite creative scenarios rather than fixed presets.
    """
    
    # Mood/Theme → Color palette mapping (generative, not prescriptive)
    MOOD_COLORS = {
        # Warm colors for positive/social moods
        'cozy': (255, 140, 0),          # Warm orange
        'social': (255, 165, 0),         # Orange
        'happy': (255, 215, 0),          # Gold
        'cheerful': (255, 200, 0),       # Bright gold
        
        # Cool colors for calm/peaceful moods
        'calm': (100, 149, 237),         # Cornflower blue
        'peaceful': (34, 139, 34),       # Forest green
        'meditation': (72, 209, 204),    # Medium turquoise
        'relaxing': (135, 206, 250),     # Light sky blue
        
        # Purple for mysterious/magical
        'mysterious': (138, 43, 226),    # Blue violet
        'magical': (147, 51, 234),       # Purple
        'mystical': (75, 0, 130),        # Indigo
        'spooky': (75, 0, 130),          # Indigo
        
        # Red/Orange for intense/action
        'intense': (255, 69, 0),         # Red orange
        'exciting': (255, 100, 0),       # Orange red
        'battle': (255, 0, 0),           # Pure red
        'danger': (255, 0, 0),           # Bright red
        
        # Blues/teals for water/eerie
        'eerie': (0, 100, 150),          # Dark teal
        'ghostly': (0, 100, 150),        # Dark teal
        'nautical': (0, 100, 150),       # Dark teal blue
        'ocean': (0, 150, 200),          # Lighter teal
        'underwater': (0, 200, 200),     # Cyan
        
        # Neutral for ambient
        'ambient': (128, 128, 128),      # Gray
        'neutral': (150, 150, 150),      # Light gray
        'focus': (100, 200, 255),        # Light blue
    }
    
    # Intensity levels → Effects and brightness
    INTENSITY_EFFECTS = {
        'very_calm': {'effect': 'steady', 'brightness': 100},
        'calm': {'effect': 'steady', 'brightness': 150},
        'normal': {'effect': 'steady', 'brightness': 180},
        'active': {'effect': 'shimmer', 'brightness': 200},
        'energetic': {'effect': 'pulse', 'brightness': 220},
        'intense': {'effect': 'strobe', 'brightness': 255},
    }
    
    @staticmethod
    def extract_keywords(text: str) -> Dict[str, list]:
        """Extract mood/theme keywords from Kai's ambiance description"""
        text_lower = text.lower()
        
        keywords = {
            'mood': [],
            'setting': [],
            'intensity': [],
            'elements': [],
        }
        
        # Detect moods
        mood_words = ['cozy', 'social', 'happy', 'cheerful', 'calm', 'peaceful', 
                      'meditative', 'relaxing', 'mysterious', 'magical', 'mystical',
                      'spooky', 'eerie', 'ghostly', 'intense', 'exciting', 'battle',
                      'danger', 'nautical', 'ocean', 'underwater', 'ambient', 'focus']
        for word in mood_words:
            if word in text_lower:
                keywords['mood'].append(word)
        
        # Detect settings
        setting_words = ['tavern', 'inn', 'pub', 'bar', 'forest', 'woods', 'jungle',
                        'dungeon', 'cave', 'castle', 'palace', 'throne', 'ship', 'boat',
                        'desert', 'mountain', 'tundra', 'volcano', 'temple', 'ruins',
                        'graveyard', 'cemetery', 'house', 'mansion', 'village', 'city']
        for word in setting_words:
            if word in text_lower:
                keywords['setting'].append(word)
        
        # Detect intensity
        if any(word in text_lower for word in ['intense', 'epic', 'extreme', 'battle', 'fight', 'combat']):
            keywords['intensity'].append('intense')
        elif any(word in text_lower for word in ['exciting', 'energetic', 'action', 'rush']):
            keywords['intensity'].append('energetic')
        elif any(word in text_lower for word in ['calm', 'peaceful', 'meditative', 'relax']):
            keywords['intensity'].append('very_calm')
        elif any(word in text_lower for word in ['mysterious', 'eerie', 'spooky', 'creepy']):
            keywords['intensity'].append('active')
        else:
            keywords['intensity'].append('normal')
        
        # Detect special elements
        element_words = ['ghost', 'pirate', 'music', 'sound', 'ambient', 'magic', 'fire', 'water']
        for word in element_words:
            if word in text_lower:
                keywords['elements'].append(word)
        
        return keywords
    
    @staticmethod
    def generate_music_prompt(text: str, keywords: Dict[str, list]) -> str:
        """
        Generate a dynamic YouTube music search prompt based on Kai's input.
        Kai has already analyzed the conversation; we just need to create a good search.
        """
        # If Kai already provided music prompt, use it as base
        # Otherwise, construct from keywords
        
        # Start with base description
        parts = []
        
        # Add setting if detected
        if keywords['setting']:
            parts.append(' '.join(keywords['setting']))
        
        # Add mood
        if keywords['mood']:
            parts.append(' '.join(keywords['mood']))
        
        # Add special words from original text
        if keywords['elements']:
            parts.append(' '.join(keywords['elements']))
        
        # Build search query
        if parts:
            search = ' '.join(parts) + ' ambient music'
        else:
            # Use original text as fallback
            search = text + ' ambient music'
        
        logger.info(f"Generated music prompt: {search}")
        return search
    
    @staticmethod
    def generate_lighting_config(keywords: Dict[str, list], intensity_override: str = None) -> Dict[str, Any]:
        """
        Generate lighting config (color, effect, brightness) from keywords.
        
        Returns:
            {'color': (R, G, B), 'effect': 'steady'|'shimmer'|'pulse'|'strobe'|'flicker', 'brightness': 0-255}
        """
        
        # Determine primary color from first mood keyword
        color = (150, 150, 150)  # Default gray
        if keywords['mood']:
            mood = keywords['mood'][0]
            color = KaiCommandInterpreter.MOOD_COLORS.get(mood, color)
        
        # If setting suggests a specific color
        if keywords['setting']:
            setting = keywords['setting'][0]
            if setting in ['ocean', 'sea', 'ship', 'water', 'underwater']:
                color = (0, 150, 200)  # Teal/cyan
            elif setting in ['forest', 'woods', 'jungle']:
                color = (34, 139, 34)  # Forest green
            elif setting in ['desert']:
                color = (218, 165, 32)  # Goldenrod
            elif setting in ['volcano', 'fire']:
                color = (255, 69, 0)    # Red orange
            elif setting in ['graveyard', 'cemetery', 'dungeon']:
                color = (75, 0, 130)    # Indigo
            elif setting in ['castle', 'palace', 'throne']:
                color = (200, 150, 100) # Gold
            elif setting in ['tavern', 'inn', 'pub']:
                color = (255, 140, 0)   # Warm orange
        
        # Determine effect and brightness from intensity
        intensity = intensity_override or keywords['intensity'][0] if keywords['intensity'] else 'normal'
        effect_config = KaiCommandInterpreter.INTENSITY_EFFECTS.get(intensity, {'effect': 'steady', 'brightness': 180})
        
        # Special effect: flicker for eerie/ghostly
        if 'eerie' in keywords['mood'] or 'ghostly' in keywords['mood']:
            effect_config['effect'] = 'flicker'
        elif 'shimmer' not in effect_config['effect'] and any(word in keywords['mood'] for word in ['peaceful', 'calm']):
            effect_config['effect'] = 'shimmer'
        
        return {
            'color': color,
            'effect': effect_config['effect'],
            'brightness': effect_config['brightness'],
        }
    
    @staticmethod
    def interpret_dnd_ambiance(prompt: str, confidence: float = 0.8) -> Dict[str, Any]:
        """
        Dynamically interpret any D&D ambiance prompt.
        
        Args:
            prompt: Natural language from Kai (e.g., "A spooky haunted ship on the ocean")
            confidence: Kai's confidence in this interpretation
        
        Returns:
            Dictionary with dynamically generated music_query and lighting config
        """
        logger.info(f"📝 Interpreting ambiance: {prompt}")
        
        # Extract keywords from the prompt
        keywords = KaiCommandInterpreter.extract_keywords(prompt)
        logger.info(f"   Detected keywords: mood={keywords['mood']}, setting={keywords['setting']}, intensity={keywords['intensity']}")
        
        # Generate music search prompt
        music_query = KaiCommandInterpreter.generate_music_prompt(prompt, keywords)
        
        # Generate lighting config
        lighting_config = KaiCommandInterpreter.generate_lighting_config(keywords)
        
        logger.info(f"✅ Generated scene config:")
        logger.info(f"   Music: {music_query}")
        logger.info(f"   LED: {lighting_config['color']} {lighting_config['effect']} @ {lighting_config['brightness']}")
        
        return {
            'music_query': music_query,
            'lighting': lighting_config,
            'confidence': confidence,
        }
    
    @staticmethod
    def interpret_play_mood(mood_description: str, confidence: float = 0.8) -> Dict[str, Any]:
        """
        Interpret mood-based request (more general than D&D).
        
        Args:
            mood_description: Kai's description of desired mood
            confidence: How confident Kai is
        
        Returns:
            Dictionary with music and lighting
        """
        
        keywords = KaiCommandInterpreter.extract_keywords(mood_description)
        music_query = KaiCommandInterpreter.generate_music_prompt(mood_description, keywords)
        lighting_config = KaiCommandInterpreter.generate_lighting_config(keywords)
        
        return {
            'music_query': music_query,
            'lighting': lighting_config,
            'confidence': confidence,
        }
        
        # Default to ambient if unknown mood
        logger.warning(f"⚠️  Unknown mood '{mood}', using ambient")
        return mood_configs['ambient']
