## tl;dr
At four BHD12 seats, the provisional BHD10 fixed fee breaks even only when venue contribution margin covers the fee plus per-table overhead. With BHD5 overhead the threshold is 31.25%; at the central 40% assumption, at least 78.125% of seats must be net-new and modeled contribution is BHD4.20. All margins, overheads, compensation terms, and setup allowance are sensitivities, not observed costs.

## Context & Methods
Sponsor-attested inputs are BHD12 minimum spend, four players per average table, two filled tables weekly, venue ownership, and player/DM/schedule-fit constraints. The model compares fixed fee, share of gross, venue credit at face value, and volunteer labor at a recorded shadow value.

### Key Assumptions
Contribution margin: 25%, 40%, 55%, 70%. Other incremental overhead: BHD0, BHD5, BHD10. Central case: 40% and BHD5. Setup recovery allowance: BHD20. None is claimed as actual venue performance.

In [1]:
import runpy
model = runpy.run_path('fsc_legacy_yes_001_dm_compensation_sensitivity.py')
summary = model['model_summary']
facts = summary['sponsor_attested']
rec = summary['recommended_default_pending_sponsor']
print(f"BHD{facts['minimum_spend_per_player_bhd'] * facts['average_players_per_table']:.2f} gross per full table; BHD{facts['current_minimum_weekly_gross_bhd']:.2f} current weekly gross floor")
print(f"Recommended threshold: {rec['minimum_four_seat_margin_required']:.2%}; net-new threshold: {rec['minimum_net_new_player_fraction_required']:.3%}; central net: BHD{rec['central_case_net_per_table_bhd']:.2f}; break-even: {rec['central_case_break_even_seats']} seats")

BHD48.00 gross per full table; BHD96.00 current weekly gross floor
Recommended threshold: 31.25%; net-new threshold: 78.125%; central net: BHD4.20; break-even: 4 seats


## Data
The full scenario ledger is generated by the companion Python model. The selected rows below make each structure directly comparable at the central case.

In [2]:
selected = [('fixed_fee', 10.0), ('gross_revenue_share', 0.15), ('venue_credit', 12.0), ('volunteer_shadow_value', 10.0)]
for row in model['central_scenarios']:
    if (row['structure'], row['value']) in selected:
        print(f"{row['structure']} {row['display_value']}: cost BHD{row['dm_cost_bhd']:.2f}, net BHD{row['net_contribution_bhd']:.2f}, break-even {row['break_even_seats']} seats")

fixed_fee BHD10: cost BHD10.00, net BHD4.20, break-even 4 seats
gross_revenue_share 15% of gross: cost BHD7.20, net BHD7.00, break-even 2 seats
venue_credit BHD12: cost BHD12.00, net BHD2.20, break-even 4 seats
volunteer_shadow_value BHD10: cost BHD10.00, net BHD4.20, break-even 4 seats


## Results
Fixed fee is the safest default because it is capped, legible, and attributable to delivery. Gross share can preserve headroom at low rates but introduces reconciliation and DM-attractiveness uncertainty. Credit may cost less than face value, but only actual COGS can prove that. Volunteer hosting is not treated as zero-cost merely because cash does not move.

In [3]:
for margin in model['CONTRIBUTION_MARGINS']:
    rows = [r for r in model['recommended_sensitivity'] if r['margin'] == margin]
    values = ', '.join(f"BHD{r['four_seat_net_bhd']:.2f}" for r in rows)
    print(f"{margin:.0%} margin: {values} at overhead BHD0/5/10")

25% margin: BHD2.00, BHD-3.00, BHD-8.00 at overhead BHD0/5/10
40% margin: BHD9.20, BHD4.20, BHD-0.80 at overhead BHD0/5/10
55% margin: BHD16.40, BHD11.40, BHD6.40 at overhead BHD0/5/10
70% margin: BHD23.60, BHD18.60, BHD13.60 at overhead BHD0/5/10


## Takeaways
Measure actual contribution margin and net-new-player share before a live DM offer. Default provisionally to BHD10 fixed per approved, delivered session and do not stack credit. If measured margin is below 31.25% or net-new seats below 78.125% in the central case, revise or stop rather than adding seats. The fee implies only BHD2.50–4.00/hour over 2.5–4 hours, so DM acceptance is unverified.