name: Test Service Account

on:
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Service Account JSON
      run: |
        echo "Testing service account JSON format..."
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' > test-service-account.json
        
        # Check if it's valid JSON
        if jq . test-service-account.json; then
          echo "✅ Service account JSON is valid"
        else
          echo "❌ Service account JSON is invalid"
        fi
        
        # Check required fields
        echo "Checking required fields..."
        jq -r '.type' test-service-account.json
        jq -r '.project_id' test-service-account.json
        jq -r '.client_email' test-service-account.json
        
        # Cleanup
        rm test-service-account.json